- hosts: all
  become: yes
  tasks:
    - name: install Docker
      become: yes
      script: ../admin-scripts/docker-install.sh
    
    - name: allow 'golubyatnikov' to have access to Docker
      become: yes  
      shell: usermod -aG docker golubyatnikov
